<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE troubleshooting PUBLIC "-//OASIS//DTD DITA Troubleshooting//EN" "troubleshooting.dtd">
<troubleshooting id="itm_vm_interface_authorization_problem">
    <title>Не удается зайти в веб-интерфейс DATAPK ITM-VM с корректными учетными данными</title>
    <troublebody>
        <condition id="condition_bk3_ysm_4xb">
            <p>В качестве причин недоступности веб-интерфейса <ph outputclass="udvpdf"><term
                        keyref="udv_itm_k"/></ph><ph outputclass="onlypdf"><term
                        keyref="datapk_itm_k"/></ph><ph outputclass="html"><term
                        keyref="datapk_itm_k"/></ph> рассмотрены следующие:<ul id="ul_m22_ftm_4xb">
                    <li>Не задано значение переменной <cmdname keyref="itmm_password_secret_key"/> в
                        файле <codeph>.itmm_password_secret_key</codeph> либо переменная <cmdname
                            keyref="itmm_password_secret_key"/> закомментирована.</li>
                    <li>
                        <p>В файле <codeph>pg_hba.conf</codeph> указано значение только для одной
                            базы данных, а не для нескольких.</p>
                    </li>
                    <li>Модуль управления парольными политиками «securityprofile» не был повторно
                        инициализирован после перезагрузки сервера СУБД или перезапуска службы
                        jatoba-1.</li>
                </ul></p>
        </condition>
        
        <troubleSolution>
            <cause>
                <title>Причина 1</title>
                <p>Не задано значение переменной <cmdname keyref="itmm_password_secret_key"/> в
                    файле <codeph>.itmm_password_secret_key</codeph> либо переменная <cmdname
                        keyref="itmm_password_secret_key"/> закомментирована.</p>
                
            </cause>
            <cause>
                <title>Описание проблемы</title>
                <p>Не удается зайти в веб-интерфейс <abbreviated-form keyref="datapk_itm_vm"/> с
                    корректными учетными данными. При запуске контейнеров <abbreviated-form
                        keyref="datapk_itm_vm"/> командой <codeph>docker-compose up -d</codeph>
                    происходит одно из следующих действий:<ul id="ul_f5l_bb3_5tb">
                        <li>В консоли выводится сообщение: «The <cmdname
                                keyref="itmm_password_secret_key"/> variable is not set. Defaulting
                            to a blank string.». </li>
                        <li>Перезапускаются контейнеры itm_m_zabbix_connector,
                            itm_m_notifier_service, itm_m_user_service. В логах
                            itm_m_zabbix_connector содержится запись вида: «Значение поля "key"
                            (Ключ для шифрования паролей) из переменной окружения <cmdname
                                keyref="itmm_password_secret_key"/> не прошло валидацию: Значение
                            должно равняться 32 байтам. Текущая длина — &lt;...> байт».</li>
                    </ul></p>
                
            </cause>
            <remedy>
                <title>Способ устранения</title>
                <responsibleParty/>
                <steps id="steps_dwq_2tm_4xb">
                    <step
                        conref="../reusable/notes/docker_compose_down.dita#ReusableComponent_nqz_233_zrb/step_oqz_233_zrb">
                        <cmd/>
                    </step>
                    <step>
                        <cmd>Сгенерируйте новый ключ для шифрования и дешифрования паролей:</cmd>
                        <info>
                            <codeblock>LC_ALL=C tr -dc 'A-Za-z0-9!$%^*' &lt;/dev/urandom | head -c 32 ; echo ''</codeblock>
                        </info>
                    </step>
                    <step>
                        <cmd>Откройте для редактирования файл
                                <codeph>.itmm_password_secret_key</codeph>. </cmd>
                    </step>
                    <step>
                        <cmd>Удалите старый ключ.</cmd>
                        <info>
                            <note type="attention">При повторном изменении или утере значения
                                переменной <cmdname keyref="itmm_password_secret_key"/> локальные
                                пользователи не смогут войти в веб-интерфейс <ph
                                    outputclass="udvpdf"><term keyref="udv_itm_vm"/></ph><ph
                                    outputclass="onlypdf"><term keyref="datapk_itm_vm"/></ph><ph
                                    outputclass="html"><term keyref="datapk_itm_vm"/></ph>,
                                перестанет работать синхронизация с <ph outputclass="udvpdf"><term
                                        keyref="udv_itm_k"/></ph><ph outputclass="onlypdf"><term
                                        keyref="datapk_itm_k"/></ph><ph outputclass="html"><term
                                        keyref="datapk_itm_k"/></ph>, <ph
                                    conref="../reusable/protocol_names/LDAP.dita#ReusableComponent_jnq_hm4_pyb/ph_knq_hm4_pyb"
                                /> и <ph
                                    conref="../reusable/protocol_names/SMTP.dita#ReusableComponent_mss_sdg_4yb/ph_nss_sdg_4yb"
                                />.</note>
                        </info>
                    </step>
                    <step>
                        <cmd>Вставьте новый ключ.</cmd>
                    </step>
                    <step>
                        <cmd>Сохраните изменения и закройте файл
                                <codeph>.itmm_password_secret_key</codeph>. </cmd>
                    </step>
                    <step>
                        <cmd>Обратитесь в техподдержку по адресу <i>itm@ussc.ru</i> и запросите
                            скрипт для удаления баз данных.</cmd>
                    </step>
                </steps>
            </remedy>
        </troubleSolution>
        <troubleSolution>
            <cause>
                <title>Причина 2</title>
                <p>В файле <codeph>pg_hba.conf</codeph> указано следующее значение для подключения:
                    <codeblock>host itmm itmm_user 172.15.0.1/24 md5</codeblock></p>
                <p>Это значение подходит только для одной базы данных, нужно разрешить подключение
                    для нескольких баз данных.</p>
            </cause>
            <cause>
                <title>Описание проблемы</title>
                <p>При попытке зайти в веб-интерфейс <abbreviated-form keyref="datapk_itm_vm"/>
                    выводится сообщение «Внутренняя ошибка сервера». При вызове окна «инструменты
                    разработчика» через F12 выводятся сообщения о некорректном шлюзе. </p>
                <p>При этом контейнеры не перезапускаются, в контейнере itm_m_user_service ошибка
                    вида: </p>
                <codeblock>"Не удалось подключиться к БД postgresql+asyncpg//postgres:**********@host.docker.internal:10265/user_service - 
в pg_hba.conf нет записи для компьютера "172.15.0.6", пользователя "itmm_user", базы "user_service", SSL выкл."</codeblock>
            </cause>
            <remedy>
                <title>Способ устранения</title>
                <responsibleParty/>
                <steps id="steps_kgm_b5m_4xb">
                    <step
                        conref="../../topics/reusable/notes/container_stop.dita#ReusableComponent_v5l_qws_rrb/step_w5l_qws_rrb">
                        <cmd/>
                    </step>
                    <step>
                        <cmd>Отредактируйте файл <codeph
                            conref="../../topics/reusable/filepath/pg_hba_conf.dita#ReusableComponent_gtb_nxd_yrb/codeph_htb_nxd_yrb"
                            />:</cmd>
                        <substeps id="substeps_vt4_qbl_ctb">
                            <substep>
                                <cmd>Перейдите в режим редактирования файла:</cmd>
                                <info>
                                    <codeblock>vi /var/lib/jatoba/1/data/pg_hba.conf</codeblock>
                                </info>
                            </substep>
                            <substep>
                                <cmd>Найдите строку, вызывающую ошибку:</cmd>
                                <info>
                                    <codeblock>host itmm [имя пользователя БД] 172.15.0.1/24 md5</codeblock>
                                </info>
                                <stepxmp>для пользователя itmm_user строка будет иметь вид:
                                    <codeblock>host itmm itmm_user 172.15.0.1/24 md5</codeblock></stepxmp>
                            </substep>
                            <substep>
                                <cmd>Отредактируйте строку, чтобы установить подключение к
                                    нескольким БД:</cmd>
                                <info>
                                    <codeblock>host all [имя пользователя БД] 172.15.0.1/24 md5</codeblock>
                                </info>
                            </substep>
                            <substep
                                conref="../../topics/reusable/notes/save_and_exit.dita#ReusableComponent_n4j_pxx_xrb/substep_p4j_pxx_xrb">
                                <cmd/>
                            </substep>
                        </substeps>
                    </step>
                    <step
                        conref="../../topics/reusable/notes/jatoba_restart.dita#ReusableComponent_wrm_nj3_zrb/step_xrm_nj3_zrb">
                        <cmd/>
                    </step>
                    <step conref="../../topics/reusable/notes/container_run.dita#ReusableComponent_prv_5ws_rrb/step_qrv_5ws_rrb">
                        <cmd/>
                        <info> </info>
                    </step>
                </steps>
            </remedy>
        </troubleSolution>
        <troubleSolution>
            <cause>
                <title>Причина 3</title>
                <p>Модуль управления парольными политиками «securityprofile» не был повторно
                    инициализирован после перезагрузки сервера СУБД или перезапуска службы
                    jatoba-1.</p>
                
            </cause>
            <cause>
                <title>Описание проблемы</title>
                <p>После перезагрузки сервера СУБД или перезапуска службы jatoba-1 не удается зайти
                    в веб-интерфейс <ph outputclass="udvpdf"><term keyref="udv_itm_vm"/></ph><ph
                        outputclass="onlypdf"><term keyref="datapk_itm_vm"/></ph><ph
                        outputclass="html"><term keyref="datapk_itm_vm"/></ph> с корректными
                    учетными данными. При попытке авторизации в веб-интерфейсе появляется сообщение
                    «Внутренняя ошибка сервера», а в логах СУБД, расположенных в директории
                        <codeph>/var/lib/jatoba/1/data/log</codeph>, содержится ошибка «FATAL:
                    Extension securityprofile need to be initialized by superuser.».</p>
            </cause>
            <remedy>
                <title>Способ устранения</title>
                <responsibleParty>Повторно инициализируйте модуль управления парольными политиками
                    пользователей СУБД «securityprofile». Для этого:</responsibleParty>
                <steps id="steps_v5v_q5m_4xb">
                    <step>
                        <cmd>Войдите в интерактивный терминал для работы с postgresql под
                            пользователем <codeph>postgres</codeph>:</cmd>
                        <info>
                            <codeblock>sudo -u postgres psql -p 10265 -h 127.0.0.1 -U [имя пользователя] [имя базы]</codeblock>
                            <p>Где:</p>
                            <ul id="ul_w5v_q5m_4xb">
                                <li><codeph>-u postgres</codeph> — пользователь ОС;</li>
                                <li><codeph>-p 10265</codeph> — порт, через который будет
                                    произведено подключение к базе данных;</li>
                                <li><codeph>-h 127.0.0.1</codeph> — подключение к хосту
                                    127.0.0.1;</li>
                                <li><codeph>-U [имя пользователя]</codeph> — подключение от имени
                                    указанного пользователя.</li>
                            </ul>
                        </info>
                    </step>
                    <step>
                        <cmd>Инициализируйте модуль «securityprofile» c помощью команды:</cmd>
                        <itemgroup>
                            <codeblock>SELECT SECURITYPROFILE.SYNCHRONIZE();</codeblock>
                        </itemgroup>
                    </step>
                    <step>
                        <cmd>Покиньте терминал:</cmd>
                        <itemgroup>
                            <codeblock>\q</codeblock>
                        </itemgroup>
                    </step>
                </steps>
            </remedy>
        </troubleSolution>
    </troublebody>
</troubleshooting>
